#!/usr/bin/env bash
set -euxo pipefail

TEMP_DIR="$(mktemp -d)"

APP_VERSION="26.707.31428"
DOWNLOAD_URL="https://persistent.oaistatic.com/codex-app-prod/ChatGPT-darwin-arm64-$APP_VERSION.zip"
if command -v aria2c >/dev/null; then
  aria2c --continue=true --split=16 --max-connection-per-server=16 \
    --min-split-size=1M --file-allocation=none \
    --dir "$TEMP_DIR" --out file.zip "$DOWNLOAD_URL"
else
  curl -o "$TEMP_DIR/file.zip" "$DOWNLOAD_URL"
fi

HOSTED_CODEX_APP_ZIP="$TEMP_DIR/file.zip" bash ./scripts/prepare_asar

rm -rf "$TEMP_DIR"
